//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by the MSBuild WriteCodeFragment class.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: AssemblyInformationalVersionAttribute("1.2.3-test")]
[assembly: AssemblyFileVersionAttribute("1.2.3-test")]